# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ca25f5751d048421680b8c0247fa01d7d303276289d5dc2343815d1067ad1756b85f54d6a6fe1efe378d4d115dcbd0b7e0d6cdc8d488e34d1532cf442300308

test:
  secret_key_base: 1eac234c28730e94c3bdbf2885ab5e5a8e8f121d598007688dc08232c57108d665feb5f1aeb299ee792002ae2978a25a02ad6e8aec8519be9cee8d631678b644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
